name: Executar comando CMD no Self-Hosted Runner

on:
  workflow_dispatch: # Permite disparar manualmente

jobs:
  executar-cmd:
    runs-on: self-hosted  # Usa um runner self-hosted
    name: Executar comando no CMD do Windows
    steps:
      - name: Verificar o runner
        run: cd D:\protheus\compila ; ./appserver.exe -compile -files=D:\protheus\src -includes=D:\protheus\includes -env=compila
