name: Executar comando CMD no Self-Hosted Runner

on:
  workflow_dispatch: # Permite disparar manualmente

jobs:
  executar-cmd:
    runs-on: self-hosted  # Usa um runner self-hosted
    name: Executar comando no CMD do Windows
    steps:
      - uses: actions/checkout@v4
      - name: Compila projeto
        run: cd D:\protheus\compila ; rm console.log ; ./appserver.exe -compile -files=C:\actions-runner\_work\compile\compile -includes=D:\protheus\includes -env=compila -outreport
      - name: Verifica se existem erros
        run : if ((Get-Content -Path D:\protheus\compila\cmdreport\compile_errors.log).Length -gt 0) { exit 1 } else { echo sucesso} ; Get-Content -Path D:\protheus\compila\cmdreport\compile_errors.log
