name: Executar comando CMD no Self-Hosted Runner

on:
  workflow_dispatch: # Permite disparar manualmente

jobs:
  executar-cmd:
    runs-on: self-hosted  # Usa um runner self-hosted
    name: Executar comando no CMD do Windows
    steps:
      - name: Verificar o runner
        run: echo "Rodando em ${{ runner.os }}"

      - name: Executar comando CMD no Windows
        shell: cmd
        run: |
          echo Comando sendo executado no CMD
          dir
